/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.3.144 */
/* Module Version: 5.7 */
/* Sat Apr 27 19:26:04 2019 */

/* parameterized module instance */
pllImpl __ (.CLKI( ), .RST( ), .CLKOP( ), .LOCK( ));
