/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.3.144 */
/* Module Version: 5.7 */
/* Mon Apr 22 11:06:50 2019 */

/* parameterized module instance */
pllImpl __ (.CLKI( ), .RST( ), .CLKOP( ), .LOCK( ));
